In [1]:
import numpy as np

In [2]:
arr1 = np.linspace(-np.pi,np.pi,10)
arr1

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [3]:
arr1 = np.linspace(-np.pi,np.pi,10)
arr1


array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [4]:
arr1 = np.linspace(-np.pi,np.pi,10)
arr1

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [5]:
sin_value = np.sin(arr1)

In [6]:
sin_value

array([-1.22464680e-16, -6.42787610e-01, -9.84807753e-01, -8.66025404e-01,
       -3.42020143e-01,  3.42020143e-01,  8.66025404e-01,  9.84807753e-01,
        6.42787610e-01,  1.22464680e-16])

In [7]:
sin_value = np.round(sin_value, 3)

In [8]:
sin_value

array([-0.   , -0.643, -0.985, -0.866, -0.342,  0.342,  0.866,  0.985,
        0.643,  0.   ])

using mean in numpy array

In [9]:
array1 = np.array([1, 2, 4, 6])
mean = np.mean(array1)

In [10]:
mean

np.float64(3.25)

In [11]:
array2 = np.array([[6, 7, 8, 9], [ 10, 12, 23, 23], [12, 34, 56, 67]])


In [12]:
array2

array([[ 6,  7,  8,  9],
       [10, 12, 23, 23],
       [12, 34, 56, 67]])

In [13]:
mean = np.mean(array2)
mean

np.float64(22.25)

In [14]:
mean_1 = np.mean(array2, axis = 0)
mean_1

array([ 9.33333333, 17.66666667, 29.        , 33.        ])

### random number in numpy

In [15]:
# rand
# randint


rand_array1 = np.random.rand(4)
rand_array1

array([0.6922447 , 0.1435022 , 0.65940697, 0.46945924])

In [16]:
rand_array1 = np.random.rand(4,4)
rand_array1

array([[0.27306616, 0.39702281, 0.24634327, 0.54075616],
       [0.18591124, 0.09919351, 0.39206019, 0.32085925],
       [0.92141518, 0.05317045, 0.24939515, 0.1859997 ],
       [0.48928927, 0.17183973, 0.89128121, 0.85625287]])

In [17]:
randint_array = np.random.randint(10,20, size= (4, 5))


In [18]:
randint_array

array([[10, 14, 17, 14, 17],
       [19, 12, 13, 14, 12],
       [18, 13, 19, 14, 12],
       [13, 13, 13, 16, 15]], dtype=int32)

Split() morthod in numpy array

In [19]:
import numpy as np

In [20]:
array_1 = np.random.randint(10, 51, size=(5,6))
array_1

array([[36, 16, 11, 13, 19, 45],
       [47, 50, 38, 45, 37, 10],
       [30, 45, 36, 18, 12, 25],
       [50, 39, 22, 45, 11, 27],
       [48, 22, 18, 30, 24, 22]], dtype=int32)

In [21]:
array_first, array_second = np.split(array_1, [3], axis=1)

In [22]:
array_first

array([[36, 16, 11],
       [47, 50, 38],
       [30, 45, 36],
       [50, 39, 22],
       [48, 22, 18]], dtype=int32)

In [23]:
array_columnpart1, array_columnpart2 = np.split(array_1, [3], axis=1)

In [24]:
array_columnpart1

array([[36, 16, 11],
       [47, 50, 38],
       [30, 45, 36],
       [50, 39, 22],
       [48, 22, 18]], dtype=int32)

In [25]:
array_columnpart1, array_columnpart2 , array_columnpart3 = np.split(array_1, [2,4], axis=1)

In [26]:
array_columnpart1.shape

(5, 2)

In [27]:
array_columnpart2.shape

(5, 2)

In [28]:
array_columnpart3.shape

(5, 2)

# loading the data from txt

In [29]:
iris_array = np.genfromtxt(r"C:\Users\lenovo\OneDrive\Desktop\ML\numpy\iris.txt",delimiter=',',dtype=str)

FileNotFoundError: C:\Users\lenovo\OneDrive\Desktop\ML\numpy\iris.txt not found.

In [ ]:
iris_array

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [ ]:
features, labels = np.split(iris_array,[4], axis=1)


In [ ]:
features

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2'],
       ['5.4', '3.9', '1.7', '0.4'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['4.9', '3.1', '1.5', '0.1'],
       ['5.4', '3.7', '1.5', '0.2'],
       ['4.8', '3.4', '1.6', '0.2'],
       ['4.8', '3.0', '1.4', '0.1'],
       ['4.3', '3.0', '1.1', '0.1'],
       ['5.8', '4.0', '1.2', '0.2'],
       ['5.7', '4.4', '1.5', '0.4'],
       ['5.4', '3.9', '1.3', '0.4'],
       ['5.1', '3.5', '1.4', '0.3'],
       ['5.7', '3.8', '1.7', '0.3'],
       ['5.1', '3.8', '1.5', '0.3'],
       ['5.4', '3.4', '1.7', '0.2'],
       ['5.1', '3.7', '1.5', '0.4'],
       ['4.6', '3.6', '1.0', '0.2'],
       ['5.1', '3.3', '1.7', '0.5'],
       ['4.8', '3.4', '1.9', '0.2'],
       ['5.0', '3.0', '1.6', '0.2'],
       ['5.0', '3.4', '1.6', '0.4'],
 

In [ ]:
labels.shape

(150, 1)

In [ ]:
features.shape

(150, 4)

In [ ]:
features[:5]

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2']], dtype='<U15')

In [ ]:
labels[:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype='<U15')

In [ ]:
features = features.astype(float)

In [ ]:
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
mean_feature = np.mean(features,axis=0)

In [ ]:
mean_feature

array([5.84333333, 3.054     , 3.75866667, 1.19866667])