In [65]:
import numpy as np

### creating numpy array 


In [66]:
arr1 = np.array([[3,5,6,8,10]])
print(arr1)
print(type(arr1))

[[ 3  5  6  8 10]]
<class 'numpy.ndarray'>


### creating two dimensional array


In [67]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)
print(type(array_2d))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [68]:
array_3d = np.array([[1,3,4],[4,5,6],[7,8,9],[1,11,12]])
print(array_3d)
print(type(array_3d))


[[ 1  3  4]
 [ 4  5  6]
 [ 7  8  9]
 [ 1 11 12]]
<class 'numpy.ndarray'>


In [69]:
aar_100 = np.arange(1,101)
aar_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [70]:
aar2 = np.linspace(1,5,10)
print(aar2)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [71]:
#### creating zero,one and identity matrix


In [72]:
arr_zero = np.zeros([8,8])
arr_zero

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
arr_ones = np.ones([8,8],dtype=int)
arr_ones

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [74]:
arr_identity = np.eye((8))
arr_identity

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [75]:
array_3d.shape


(4, 3)

In [76]:
arr_identity.shape

(8, 8)

In [77]:
arr1 = np.array((1,2,3))
arr2 = np.array((2,3,6))
add = arr1+arr2
add


array([3, 5, 9])

In [78]:
arr121 = np.array(([3,4,5],[5,6,7],[8,9,10]))
arr345 = np.array(([1,2,3],[4,5,6],[7,8,9]))
product = arr121*arr345
product

array([[ 3,  8, 15],
       [20, 30, 42],
       [56, 72, 90]])

## multidimensional array


In [79]:
array1 = np.array([2,3,4,5],ndmin=5)
array1

array([[[[[2, 3, 4, 5]]]]])

In [80]:
array1.shape

(1, 1, 1, 1, 4)

## operation in array


In [81]:
array1 = np.array([4,8,9,12])
print(array1 + 10)
### vectorization in numpy array

[14 18 19 22]


## slicing operation

In [82]:
array1

array([ 4,  8,  9, 12])

In [83]:
print(array1[1])

8


In [84]:
array2 = np.array([[1,2,3,4],[6,7,8,9],[10,11,12,12]])
array2

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 12]])

In [85]:
print(array2[1][1])

7


# slicing in 2 d array

In [86]:
#array2[start_row:end_row,start_coloum;end_coloum]
array2[0:2,0:4]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [87]:
array2[0:2,:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [88]:
array2[1:3,1:3]

array([[ 7,  8],
       [11, 12]])

In [89]:
array2d = np.array([[1,2,3,4],[2,4,5,6],[2,9,8,7]])


In [90]:
array2d.shape

(3, 4)

In [91]:
array2d_reshape=array2d.reshape(1,12)
array2d_reshape.shape

(1, 12)

In [92]:
array2d_1d = array2d.reshape(12)
array2d_1d


array([1, 2, 3, 4, 2, 4, 5, 6, 2, 9, 8, 7])

In [93]:
array2d_1d.reshape(6 ,2)

array([[1, 2],
       [3, 4],
       [2, 4],
       [5, 6],
       [2, 9],
       [8, 7]])

# To store 1 to 100 2dimensional array and diaplay (5,20)

In [97]:
array1d = np.arange(1 ,100)
array1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [102]:
arry2d = array1d.reshape(5, 20)
arry2d

ValueError: cannot reshape array of size 99 into shape (5,20)