In [23]:
import numpy as np

In [24]:
arr1 = np.linspace(-np.pi,np.pi,10)
arr1

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [25]:
arr1 = np.linspace(-np.pi,np.pi,10)
arr1


array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [26]:
arr1 = np.linspace(-np.pi,np.pi,10)
arr1

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [27]:
sin_value = np.sin(arr1)

In [28]:
sin_value

array([-1.22464680e-16, -6.42787610e-01, -9.84807753e-01, -8.66025404e-01,
       -3.42020143e-01,  3.42020143e-01,  8.66025404e-01,  9.84807753e-01,
        6.42787610e-01,  1.22464680e-16])

In [29]:
sin_value = np.round(sin_value, 3)

In [30]:
sin_value

array([-0.   , -0.643, -0.985, -0.866, -0.342,  0.342,  0.866,  0.985,
        0.643,  0.   ])

using mean in numpy array

In [31]:
array1 = np.array([1, 2, 4, 6])
mean = np.mean(array1)

In [32]:
mean

np.float64(3.25)

In [33]:
array2 = np.array([[6, 7, 8, 9], [ 10, 12, 23, 23], [12, 34, 56, 67]])


In [34]:
array2

array([[ 6,  7,  8,  9],
       [10, 12, 23, 23],
       [12, 34, 56, 67]])

In [35]:
mean = np.mean(array2)
mean

np.float64(22.25)

In [36]:
mean_1 = np.mean(array2, axis = 0)
mean_1

array([ 9.33333333, 17.66666667, 29.        , 33.        ])

### random number in numpy

In [37]:
# rand
# randint


rand_array1 = np.random.rand(4)
rand_array1

array([0.22346907, 0.32398875, 0.71056831, 0.65899541])

In [38]:
rand_array1 = np.random.rand(4,4)
rand_array1

array([[0.71609744, 0.53135545, 0.89484547, 0.51849219],
       [0.0415383 , 0.6878366 , 0.41678778, 0.73558067],
       [0.74104749, 0.08687516, 0.55395543, 0.41161101],
       [0.96579911, 0.91419354, 0.37019799, 0.19519316]])

In [39]:
randint_array = np.random.randint(10,20, size= (4, 5))


In [40]:
randint_array

array([[10, 12, 13, 10, 16],
       [13, 16, 14, 11, 16],
       [13, 13, 14, 16, 17],
       [10, 16, 16, 10, 15]], dtype=int32)

Split() morthod in numpy array

In [42]:
import numpy as np

In [44]:
array_1 = np.random.randint(10, 51, size=(5,6))
array_1

array([[48, 12, 49, 41, 28, 30],
       [44, 44, 49, 47, 41, 33],
       [46, 21, 13, 29, 46, 28],
       [20, 33, 16, 30, 39, 19],
       [39, 29, 31, 28, 13, 41]], dtype=int32)

In [46]:
array_first, array_second = np.split(array_1, [3], axis=1)

In [48]:
array_first

array([[48, 12, 49],
       [44, 44, 49],
       [46, 21, 13],
       [20, 33, 16],
       [39, 29, 31]], dtype=int32)

In [ ]:
array_columnpart1, array_columnpart2 = np.split(array_1, [3], axis=1)

In [52]:
array_columnpart1

array([[48, 12, 49],
       [44, 44, 49],
       [46, 21, 13],
       [20, 33, 16],
       [39, 29, 31]], dtype=int32)

In [55]:
array_columnpart1, array_columnpart2 , array_columnpart3 = np.split(array_1, [2,4], axis=1)

In [56]:
array_columnpart1.shape

(5, 2)

In [57]:
array_columnpart2.shape

(5, 2)

In [58]:
array_columnpart3.shape

(5, 2)

# loading the data from txt

In [64]:
iris_array = np.genfromtxt(r"C:\Users\lenovo\OneDrive\Desktop\ML\numpy\iris.txt",delimiter=',',dtype=str)

In [65]:
iris_array

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [66]:
features, labels = np.split(iris_array,[4], axis=1)


In [67]:
features

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2'],
       ['5.4', '3.9', '1.7', '0.4'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['4.9', '3.1', '1.5', '0.1'],
       ['5.4', '3.7', '1.5', '0.2'],
       ['4.8', '3.4', '1.6', '0.2'],
       ['4.8', '3.0', '1.4', '0.1'],
       ['4.3', '3.0', '1.1', '0.1'],
       ['5.8', '4.0', '1.2', '0.2'],
       ['5.7', '4.4', '1.5', '0.4'],
       ['5.4', '3.9', '1.3', '0.4'],
       ['5.1', '3.5', '1.4', '0.3'],
       ['5.7', '3.8', '1.7', '0.3'],
       ['5.1', '3.8', '1.5', '0.3'],
       ['5.4', '3.4', '1.7', '0.2'],
       ['5.1', '3.7', '1.5', '0.4'],
       ['4.6', '3.6', '1.0', '0.2'],
       ['5.1', '3.3', '1.7', '0.5'],
       ['4.8', '3.4', '1.9', '0.2'],
       ['5.0', '3.0', '1.6', '0.2'],
       ['5.0', '3.4', '1.6', '0.4'],
 

In [68]:
labels.shape

(150, 1)

In [69]:
features.shape

(150, 4)

In [70]:
features[:5]

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2']], dtype='<U15')

In [71]:
labels[:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype='<U15')

In [74]:
features = features.astype(float)

In [75]:
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [76]:
mean_feature = np.mean(features,axis=0)

In [77]:
mean_feature

array([5.84333333, 3.054     , 3.75866667, 1.19866667])