In [13]:
import numpy as np

In [17]:
arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array([[5,6,7,8,9]])

In [15]:
arr3 = np.concatenate([arr1, arr2], axis=0)
arr3

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [18]:
arr4 = np.concatenate([arr1, arr2], axis = 1)
arr4

array([[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]])

In [19]:
array5 = np.array([[4,5,6,7],[2,4,2,7]])
array6 = np.array([[1,2,3,4],[5,6,7,8]])


In [21]:
np.concatenate((array5, array6), axis=0)


array([[4, 5, 6, 7],
       [2, 4, 2, 7],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
np.concatenate((array5, array6), axis=1)

array([[4, 5, 6, 7, 1, 2, 3, 4],
       [2, 4, 2, 7, 5, 6, 7, 8]])

In [26]:
np.vstack((array5,array6))

array([[4, 5, 6, 7],
       [2, 4, 2, 7],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
np.hstack((array5,array6))

array([[4, 5, 6, 7, 1, 2, 3, 4],
       [2, 4, 2, 7, 5, 6, 7, 8]])

In [29]:
array7 = np.array([[1,2,3,4],[4,5,6,7]])

array8 = np.array([[2,3,4,6]])

In [32]:
np.vstack((array7 , array8))

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [2, 3, 4, 6]])

In [33]:
np.vstack((array7 , array8))


array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [2, 3, 4, 6]])

In [34]:
array9 = np.array([[10],[10]])

In [35]:
np.vstack((array7 , array9))


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 1

In [37]:
np.hstack((array7 , array9))


array([[ 1,  2,  3,  4, 10],
       [ 4,  5,  6,  7, 10]])