In [2]:
import numpy as np

In [3]:
### creating numpy array

In [4]:
arry1 = np.array([1,3,5,6,7,8])
print(arry1)
print(type(arry1))

[1 3 5 6 7 8]
<class 'numpy.ndarray'>


In [5]:
array02 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(array02)
print(type(array02))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [6]:
array_3d = np.array([[[3, 4, 5], [2, 3, 1]],
                   [[7, 8, 9], [3, 1, 4]]])
print(array_3d)

[[[3 4 5]
  [2 3 1]]

 [[7 8 9]
  [3 1 4]]]


In [7]:
arry1 = np.array([[1, 2, 3, 4],[2, 5, 6, 9]])
arry2 = np.array([[2, 4, 5, 7], [3, 4, 6, 8]])
print(arry1 * arry2)

[[ 2  8 15 28]
 [ 6 20 36 72]]


In [8]:
arry1 = np.array([[1, 2, 3, 4],[3, 4, 5, 6],[2, 5, 7, 9]])
arry2 = np.array([[9, 8, 9, 5],[6, 7, 8, 9],[3, 5, 6, 8]])
print

<function print(*args, sep=' ', end='\n', file=None, flush=False)>